# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-13 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FieldLocation',
            fields=[
                ('field_location', models.AutoField(primary_key=True, serialize=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('reservation_time', models.CharField(max_length=20)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Address', verbose_name='the address player')),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Field', verbose_name='the field player')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamAddress',
            fields=[
                ('team_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Address', verbose_name='the related player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team', verbose_name='the related team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('team_player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Player', verbose_name='the related player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team', verbose_name='the related team')),
            ],
        ),
    ]
